final/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.main),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('reviews/', include('reviews.urls')),
    path('accounts/',include('accounts.urls')),
    path('team/', include('team.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name='movies'
urlpatterns = [
    # 메인, 상세보기, 박스오피스
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.m_detail, name="m_detail"),
    path('boxoffice/', views.boxoffice, name="boxoffice"),
    
    # 영화 검색 - 입력 & 결과
    path('find/', views.find, name="find"),
    path('find2/', views.find2, name="find2"),

    # 영화 추가
    path('<int:movie_pk>/plus/', views.plus, name="plus"),
    path('find_store/', views.find_store, name="find_store"),


    # ----------- 혜민
    path('<int:movie_pk>/rate/', views.rate, name="rate"),
    path('<int:movie_pk>/rate_update/', views.rate_update, name="rate_update"),
    path('<int:movie_pk>/rate_delete/', views.rate_delete, name="rate_delete"),

    # 영화 요청
    path('please/', views.please, name="please"),
    # 영화 좋아요
    path('<int:movie_pk>/like/', views.movie_like, name="like"),
    # 추천알고리즘
    path('foryou/', views.foryou, name="foryou"),
    # 추천 메인화면
    path('recommendation/', views.recommendation, name='recommendation'),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'
urlpatterns = [
    # R: 리뷰 리스트를 보여주는 페이지
    path('', views.index, name='index'),
    # R: 특정 리뷰의 상세 내용을 보여주는 페이지  +  여기서 코멘트까지 처리
    path('<int:review_pk>/', views.review_detail, name="review_detail"),
    # C: 리뷰 작성(인자 = 영화pk)
    path('<int:movie_pk>/create/', views.review_create, name="review_create"),
    # U: 리뷰 수정
    path('<int:review_pk>/update/', views.review_update, name="review_update"),
    # D: 리뷰 삭제
    path('<int:review_pk>/delete/', views.review_delete, name="review_delete"),


    # 전체 리뷰 조회
    path('review_list/', views.review_list, name="review_list"),


    # -------------review좋아요----------- #
    path('<int:review_pk>/like/', views.review_like, name="review_like"),

    # -------------review 검색---------------- #
    path('find/', views.find, name="find"),
    path('find2/', views.find2, name="find2"),

    # -------------comment---------------- #
    path('<int:review_pk>/<int:comment_pk>/c_delete/', views.comment_delete, name='comment_delete'),
    # path('<int:review_pk>/<int:comment_pk>/c_update/', views.comment_update, name='comment_update'),
]

team/urls.py
from django.urls import path
from . import views

app_name = 'team'
urlpatterns = [
    path('', views.index, name='index'),
    path('intro/', views.intro, name='intro'),
]

reviews/models.py
from django.db import models
from movies.models import Movie
from django.conf import settings

# Create your models here.
class Review(models.Model):
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    # star = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')

    def __str__(self):
        return self.title


class Comment(models.Model):
    c_writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    content = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    clike_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments')

    def __str__(self):
        return self.content

reviews/forms.py
from django import forms
from .models import Review, Comment

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('title', 'content',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields  = ('content',)

    content = forms.CharField(
        label = 'write comment ▼',
        widget = forms.TextInput(
            attrs = {
                'placeholder' : '내용을 입력해주세요'
            }
        )
    )

reviews/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.http import HttpResponse
from django.contrib.auth import get_user_model
from django.db.models import Q
from django.db.models import Count

from .forms import ReviewForm, CommentForm
from .models import Review, Comment
from movies.models import Movie
from .serializers import ReviewSerializer
from rest_framework.response import Response
from rest_framework.decorators import api_view
from django.core.paginator import Paginator

def index(request):
    if request.user.is_authenticated:
        # 모든 리뷰
        reviews = Review.objects.all()[:5]
        # 인기 리뷰
        best_reviews = Review.objects.annotate(like_count=Count('like_users')).order_by('-like_count')[:5]
        # print(best_reviews)
        # # 인기 평론가
        User = get_user_model()
        best_reviewers = User.objects.annotate(followers_count=Count('followers')).order_by('-followers_count')[:6]
        # # 내가 쓴 글
        my_reviews = request.user.review_set.order_by('-created_at')
        # # 최근 올라온 리뷰
        recent_reviews = Review.objects.order_by('-created_at')[:5]
        context = {
            'reviews':reviews,
            'best_reviews': best_reviews,
            'best_reviewers':best_reviewers,
            'recent_reviews':recent_reviews,
            'my_reviews':my_reviews,
        }
        return render(request, 'reviews/index.html', context)
    else:
        return redirect('accounts:login')

def review_list(request):
    print("1번")
    if request.user.is_authenticated:
        # 모든 리뷰
     
        reviews = Review.objects.all() 
        paginator = Paginator(reviews, 10)	# articles를 1page당 10개씩    
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)	# 페이지는 나눠주는 obj
        context = {
            'reviews':reviews,
            'page_obj':page_obj,
           }
        return render(request, 'reviews/review_list.html', context)
    else:
        return redirect('accounts:login')

def review_create(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.user.is_authenticated:
        if request.method == "POST":
            form = ReviewForm(request.POST)
            if form.is_valid():
                review = form.save(commit=False)
                review.writer = request.user
                review.movie = get_object_or_404(Movie, pk=movie_pk)
                review.save()
                return redirect('reviews:review_detail', review.pk)
        else:
            form = ReviewForm()
        context = {
            'form':form,
            'movie':movie,
        }
        return render(request, 'reviews/forms.html', context)
    else:
        return redirect('accounts:login')

def review_update(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.user == review.writer:
        if request.method == "POST":
            form = ReviewForm(request.POST, instance=review)
            if form.is_valid():
                review = form.save(commit=False)
                review.writer = request.user
                review.save()
                return redirect('reviews:review_detail', review.pk)
        else:
            form = ReviewForm(instance=review)
        context = {
            'review':review,
            'form':form,
        }
        return render(request, 'reviews/forms.html', context)
    else:
        return redirect('reviews:review_detail', review.pk)

def review_detail(request, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        if request.method == 'POST':
            commentform = CommentForm(request.POST)
            if commentform.is_valid():
                comment = commentform.save(commit=False)
                comment.c_writer = request.user
                comment.review = review
                comment.save()
                return redirect('reviews:review_detail', review.pk)
        else:
            commentform = CommentForm()
        context = {
            'review':review,
            'commentform':commentform
        }
        return render(request, 'reviews/review_detail.html', context)
    else:
        return redirect('accounts:login')

def review_delete(request, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        if request.user == review.writer:
            review.delete()
            return redirect('reviews:index')
        else:
            return redirect('reviews:review_detail', review.pk)
    else:
        return redirect('accounts:login')

# review에 좋아요
def review_like(request, review_pk):
    if request.user.is_authenticated:
        user = request.user # 현재 로그인한 유저
        review = get_object_or_404(Review, pk=review_pk)

        if review.like_users.filter(pk=user.pk).exists():
            review.like_users.remove(user) # 좋아요 취소
            liked = False
        else:
            review.like_users.add(user) # 좋아요!
            liked = True
        data = {
            'liked':liked,
            'count':review.like_users.count(),
        }
        return JsonResponse(data)

# comment
def comment_delete(request, review_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.c_writer:
            comment.delete()
            return redirect('reviews:review_detail', review_pk)
        else:
            return redirect('reviews:review_detail', review_pk)
    else:
        return redirect('accounts:login')

def find(request):
    return render(request, 'movies/find.html')

def find2(request):
    b = request.GET.get('b','') 
    if b:
        reviews = Review.objects.filter(Q(title__icontains=b)|Q(content__icontains=b))
    else:
        reviews = '검색어와 일치하는 결과가 없습니다.'
    context = {
        'keyword':b,
        'reviews': reviews,
    }
    return render(request, 'reviews/findresult.html', context)

reviews/templates/reviews/findresult.html
{% extends 'base.html' %}

{% block content %}

<!-- md일때 -->
<div class="d-none d-lg-block">
    <div class="my-4 mx-2 pt-5">
        <div class="d-flex pl-4 pr-4 align-items-end">
            <div class="mx-5 px-3 w-100">
                <div class="row red-line mb-2"></div>
                <div class="row today-choice-intro-sm mb-4">리뷰 검색</div>
                <div class="row w-100">
                    <form class="form-inline my-2 my-md-0 w-100" method="get" action="{% url 'reviews:find2' %}">
                        <input class="form-control w-75" type="text" placeholder="키워드 입력" aria-label="Search" name="b" value="{{b}}" style="filter: brightness(50%);">
                        <button class="btn btn-outline-secondary w-25">SEARCH:D</button>>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="my-4 mx-2 pt-5">
        <div class="d-flex pl-4 pr-4 align-items-end">
            <div class="mx-5 px-3 w-100">
                <div class="row red-line mb-2"></div>
                <div class="row today-choice-intro-sm mb-4">검색 결과</div>
            {% if reviews.count %}
                {% for review in reviews %}
                <div class="col-6 row w-100 mx-0 my-5">
                    <div class="col-2"><img src="/static/img/profile/member.png" alt="user" class="w-75 mt-2"></div>
                    <div class="col-10">
                        <div class="row review-detail-sm-comment-writer">review by &nbsp;<u> {{ review.writer }}</u></div>
                        <div class="row review-detail-sm-comment-content"><a href="{% url 'reviews:review_detail' review.pk %}" class="review-detail-sm-comment-content-search">{{ review.movie }}</a></div>
                        <div class="row review-detail-sm-comment-created mt-2">작성 : {{ review.created_at }}</div>
                        <div class="row review-detail-sm-comment-updated">수정: {{ review.updated_at }}</div>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <div class="row container mb-4 text-muted justify-content-center text-center">
                    '{{ keyword }}' 에 대한 검색결과가 없습니다.
                </div>
            {% endif %} 
            </div>
        </div>
    </div>
</div>

<!-- md보다 작을때 -->
<div class="d-block d-lg-none mt-5">
    <div class="d-flex pl-4 pr-4 align-items-end">
        <div class="container w-100">
            <div class="row red-line mb-2"></div>
            <div class="row today-choice-intro-sm mb-4">영화 리뷰 검색</div>
            <div class="row w-100 mx-0">
                <form class="form-inline w-100 my-2 my-md-0" method="get" action="{% url 'reviews:find2' %}">
                    <input class="form-control w-75" type="text" placeholder="Search" aria-label="Search" name="b" value="{{b}}" style="filter: brightness(50%);">
                    <button class="btn btn-outline-secondary w-25"><img src="/static/img/search.png" alt="search" height="15px"></button>>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="d-block d-lg-none my-5 pb-5">
    <div class="d-flex pl-4 pr-4 align-items-end">
        <div class="container w-100">
            <div class="row red-line mb-2"></div>
            <div class="row today-choice-intro-sm mb-4">검색 결과</div>
            <div class="row w-100 mb-5 ">
                '{{ keyword }}' 에 대한 검색결과 입니다.
            </div>
            {% if reviews.count %}
                {% for review in reviews %}
                <div class="row w-100 mx-0 my-5">
                    <div class="col-3"><img src="/static/img/profile/member.png" alt="user" class="w-75 mt-2"></div>
                    <div class="col-9">
                        <div class="row review-detail-sm-comment-writer">review by &nbsp;<u> {{ review.writer }}</u></div>
                        <div class="row review-detail-sm-comment-content"><a href="{% url 'reviews:review_detail' review.pk %}" class="review-detail-sm-comment-content-search">{{ review.movie }}</a></div>
                        <div class="row review-detail-sm-comment-created mt-2">작성 : {{ review.created_at }}</div>
                        <div class="row review-detail-sm-comment-updated">수정: {{ review.updated_at }}</div>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <div class="row container mb-4 text-muted justify-content-center text-center">
                    '{{ keyword }}' 에 대한 검색결과가 없습니다.
                </div>
            {% endif %} 
        </div>       
    </div>
</div>

{% endblock %}

reviews/templates/reviews/forms.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TWEEZERS</title>
    <link rel="icon" type="image/png" sizes="16x16" href="/static/img/favicon-16x16.png">
    <link rel="stylesheet" href="{% static 'css/review_form.css' %}">
    <style>
    .formpage-link-to-home:hover {
        color: grey;
        text-decoration: none;
        cursor: pointer;
    }
    </style>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body class="special-body">
    <div class="div-for-formpage-top">
        <a href="{% url 'movies:index' %}" class="formpage-link-to-home"><img src="/static/img/logo.png" alt="" height="35px" class="nav-search-img">TWEEZERS</a>
    </div>
    <div class="div-for-formpage-bottom d-flex align-items-center">
        <div class="container w-100 div-for-form-container align-items-center">
            <div class="div-for-formpage-content mx-auto align-items-center">
                <div class="div-for-formpage-form mx-auto py-3 my-3">
                    {% if request.resolver_match.url_name == 'review_create' %}
                    <h4 class="text-white mt-2 mb-2">WRITE REVIEW</h4>
                    <div class="py-0 my-0 review-create-style mb-3">「 {{ movie.title }} 」,<br>어떻게 감상하셨나요?</div>
                    {% else %}
                    <h4 class="text-white mt-2 mb-4">EDIT REVIEW</h4>
                    {% endif %}
                    <form action='' method="POST" class="login-signup-form">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <button class="btn btn-danger w-100 py-1 mb-3">확인</button>
                    </form>
                    {% if request.resolver_match.url_name == 'review_create' %}
                    <a href="{% url 'movies:m_detail' movie.pk %}" class="go-back-to-detail py-0 my-0 mb-3 text-muted"> ◀ 돌아가기</a>
                    {% else %}
                    <a href="{% url 'reviews:review_detail' review.pk %}" class="go-back-to-detail py-0 my-0 mb-3 text-muted"> ◀ 돌아가기</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.0"></script>
</body>
</html>

reviews/templates/reviews/review_detail.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}

<div class="my-5 py-5">
    <!-- 리뷰 -->
    <div class="my-4 mx-2">
        <div class="d-flex pl-4 pr-4 align-items-end">
            <div class="container">
                <div class="row red-line mb-2"></div>
                <div class="row today-choice-intro-sm mb-4">REVIEW</div>
                <!-- 리뷰 기본 정보 -->
                <div class="row">
                    <div class="d-block d-sm-none col-4"><img src="https://image.tmdb.org/t/p/original/{{ review.movie.poster_path }}" class="w-100" alt=""></div>
                    <div class="d-none d-sm-block d-lg-none col-3"><img src="https://image.tmdb.org/t/p/original/{{ review.movie.poster_path }}" class="w-100" alt=""></div>
                    <div class="d-none d-lg-block col-2"><img src="https://image.tmdb.org/t/p/original/{{ review.movie.poster_path }}" class="w-100" alt=""></div>
                    <div class="col-8">
                        <div class="row mb-1"><a href="{% url 'movies:m_detail' review.movie.pk %}" class=" review-detail-sm-movie">「 {{ review.movie.title }} 」</a></div>
                        <div class="d-block d-sm-none row review-detail-sm-title">{{ review.title }}</div>
                        <div class="d-none d-sm-block row review-detail-sm-title-2">{{ review.title }}</div>
                        <div class="row review-detail-sm-writer mb-2">written by {{ review.writer }}</div>
                        <div class="d-none d-sm-block row review-detail-sm-content mt-5">{{ review.content }}</div>
                    </div>
                </div>
                <!-- 리뷰 글 -->
                <div class="row mt-3 mb-2 d-block d-sm-none">
                    <div class="col-12 review-detail-sm-content">
                        {{ review.content }}
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="d-block d-sm-none col-12 review-detail-sm-day text-right">작성일 :{{ review.created_at }}</div>
                    <div class="d-block d-sm-none col-12 review-detail-sm-uday text-right">수정일 :{{ review.updated_at }}</div>
                    <div class="d-none d-sm-block col-12 review-detail-sm-day-lg text-right">수정일 :{{ review.updated_at }} | 작성일 :{{ review.created_at }}</div>
                    <div class="col-12 review-detail-sm-likedpeople text-right mt-4" id="follower-count-{{ review.writer.pk }}">총 {{ review.writer.followers.all|length }} 명이 작성자를 팔로우하고 있습니다.</div>
                    <div class="col-12 review-detail-sm-likedpeople text-right" id="like-count-{{ review.pk }}">총 {{ review.like_users.all|length }} 명의 이용자가 이 리뷰를 좋아합니다.</div>
                    {% if request.user.is_authenticated %}
                    <div class="col-12 text-right mt-1">
                        {% if request.user == review.writer %}
                        <a href="{% url 'reviews:review_update' review.pk %}" class="btn btn-warning btn-sm text-light px-2 py-0 ml-1">수정하기</a>
                        <a href="{% url 'reviews:review_delete' review.pk %}" class="btn btn-secondary btn-sm text-light px-2 py-0 ml-1">삭제하기</a>
                        {% else %}
                            {% if request.user in review.writer.followers.all %}
                                <a href="" data-id="{{ review.writer.pk }}" id="follow-button" class="btn btn-secondary btn-sm text-light px-2 py-0 ml-1 review-detail-sm-follow">팔로우 취소</a>
                            {% else %}
                                <a href="" data-id="{{ review.writer.pk }}" id="follow-button" class="btn btn-secondary btn-sm text-light px-2 py-0 ml-1 review-detail-sm-follow">작성자 팔로우 하기</a>
                            {% endif%}
                            {% if request.user in review.like_users.all %}
                            <i class="fas fa-heart fa-md like-button ml-2" style="color:crimson" data-id="{{ review.pk }}"></i>
                            {% else %}
                            <i class="fas fa-heart fa-md like-button ml-2" style="color:grey" data-id="{{ review.pk }}"></i>
                            {% endif %}
                        {% endif %}
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <!-- 댓글 -->
    <div class="my-4 mx-2 pt-5">
        <div class="d-flex pl-4 pr-4 align-items-end">
            <div class="container">
                <div class="row red-line mb-2"></div>
                <div class="row today-choice-intro-sm mb-4">COMMENTS</div>
                <!-- 댓글 form -->
                <div class="row">
                    <form action="" method="POST" class="col-12 review-detail-sm-form d-flex align-items-center">
                        {% csrf_token %}
                        <div class="w-75">{% bootstrap_form commentform %}</div>
                        <button class="btn btn-warning btn-sm review-detail-sm-submitbutton font-weight-bold mt-3 align-self-cend mx-1 w-25">등록</button>
                    </form>
                </div>
                <!-- 댓글 리스트 -->
                {% if review.comment_set.count %}
                <div class="row">
                    {% for comment in review.comment_set.all %}
                    <div class="review-detail-sm-comment-box ml-3 my-1"></div>
                    <div class="col-12 row my-2">
                        <div class="d-block d-sm-none col-3"><img src="/static/img/profile/member.png" alt="user" class="w-100 mt-2"></div>
                        <div class="d-none d-sm-block d-lg-none col-2"><img src="/static/img/profile/member.png" alt="user" class="w-50 mt-2"></div>
                        <div class="d-none d-lg-block col-1"><img src="/static/img/profile/member.png" alt="user" class="w-50 mt-2"></div>
                        <div class="d-block d-sm-none col-9">
                            <div class="row review-detail-sm-comment-writer">comment by &nbsp;<u> {{ comment.c_writer }}</u></div>
                            <div class="row review-detail-sm-comment-content">{{ comment.content }}</div>
                            <div class="row review-detail-sm-comment-created mt-2">작성: {{ comment.created_at }}</div>
                            <div class="row review-detail-sm-comment-updated">수정: {{ comment.updated_at }}</div>
                            {% if request.user == comment.c_writer %}
                            <div class="ml-auto d-flex justify-content-end"><a href="{% url 'reviews:comment_delete' review.pk comment.pk %}" class="review-detail-sm-comment-submit btn btn-danger p-0 px-1 m-0 mt-1 btn-sm"><img src="/static/img/delete.png" width="15px" alt="delete" class="mb-1"></a></div>
                            {% endif %}
                        </div>
                        <div class="d-none d-sm-block d-lg-none col-10">
                            <div class="row review-detail-sm-comment-writer">comment by &nbsp;<u> {{ comment.c_writer }}</u></div>
                            <div class="row review-detail-sm-comment-content">{{ comment.content }}</div>
                            <div class="row review-detail-sm-comment-created mt-2">작성: {{ comment.created_at }}</div>
                            <div class="row review-detail-sm-comment-updated">수정: {{ comment.updated_at }}</div>
                            {% if request.user == comment.c_writer %}
                            <div class="ml-auto d-flex justify-content-end"><a href="{% url 'reviews:comment_delete' review.pk comment.pk %}" class="review-detail-sm-comment-submit btn btn-danger p-0 px-1 m-0 mt-1 btn-sm"><img src="/static/img/delete.png" width="15px" alt="delete" class="mb-1"></a></div>
                            {% endif %}
                        </div>
                        <div class="d-none d-lg-block col-11">
                            <div class="row review-detail-sm-comment-writer">comment by &nbsp;<u> {{ comment.c_writer }}</u></div>
                            <div class="row review-detail-sm-comment-content">{{ comment.content }}</div>
                            <div class="row review-detail-sm-comment-created mt-2">작성: {{ comment.created_at }}</div>
                            <div class="row review-detail-sm-comment-updated">수정: {{ comment.updated_at }}</div>
                            {% if request.user == comment.c_writer %}
                            <div class="ml-auto d-flex justify-content-end"><a href="{% url 'reviews:comment_delete' review.pk comment.pk %}" class="review-detail-sm-comment-submit btn btn-danger p-0 px-1 m-0 mt-1 btn-sm"><img src="/static/img/delete.png" width="15px" alt="delete" class="mb-1"></a></div>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <div class="text-secondary text-center mt-2">아직 댓글이 없습니다. 첫 댓글을 달아주세요 :)</div>
                {% endif %}
        </div>
    </div>
</div>

    <script src="https://kit.fontawesome.com/9444b3a811.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script>
        const likeButtonList = document.querySelectorAll('.like-button')
        likeButtonList.forEach(likeButton => {
        likeButton.addEventListener('click', function(event){
            const reviewId = event.target.dataset.id
            {% if user.is_authenticated %}
            axios.get(`/reviews/${reviewId}/like/`)
            .then(response => {
                const likeCount = response.data.count
                document.querySelector(`#like-count-${reviewId}`).innerText = `총 ${likeCount} 명의 이용자가 이 리뷰를 좋아합니다.`
                if (response.data.liked === true){
                event.target.style.color = 'crimson'
                } else {
                event.target.style.color = 'grey'
                }
            })
            .catch(err => {
                console.log(err)
            })
            {% else %}
            alert('비로그인 사용자는 좋아요를 누를 수 없습니다.')
            {% endif %}
        })
        })
        const followButtonList = document.querySelectorAll('#follow-button')
        followButtonList.forEach(followButton => {
            followButton.addEventListener('click', function(event){
                event.preventDefault()
                const writerId = event.target.dataset.id
                console.log(writerId)
                {% if user.is_authenticated %}
                axios.get(`/accounts/${writerId}/follow/`)
                .then(res => {
                    const followersCount = res.data.followercount
                    document.querySelector(`#follower-count-${writerId}`).innerText = `총 ${followersCount} 명이 작성자를 팔로우하고 있습니다.`
                    if (res.data.followed === true){
                        event.target.innerText = '작성자 팔로우 취소'
                    } else {
                        event.target.innerText = '작성자 팔로우 하기'
                    }
                    console.log(res)
                })
                .catch(err => {
                    console.log(err)
                })
                {% else %}
                alert('비로그인 사용자는 팔로우를 할 수 없습니다.')
                {% endif %}
            })
        })
    </script>

{% endblock %}