final/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.main),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('reviews/', include('reviews.urls')),
    path('accounts/',include('accounts.urls')),
    path('team/', include('team.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name='movies'
urlpatterns = [
    # 메인, 상세보기, 박스오피스
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.m_detail, name="m_detail"),
    path('boxoffice/', views.boxoffice, name="boxoffice"),
    
    # 영화 검색 - 입력 & 결과
    path('find/', views.find, name="find"),
    path('find2/', views.find2, name="find2"),

    # 영화 추가
    path('<int:movie_pk>/plus/', views.plus, name="plus"),
    path('find_store/', views.find_store, name="find_store"),


    # ----------- 혜민
    path('<int:movie_pk>/rate/', views.rate, name="rate"),
    path('<int:movie_pk>/rate_update/', views.rate_update, name="rate_update"),
    path('<int:movie_pk>/rate_delete/', views.rate_delete, name="rate_delete"),

    # 영화 요청
    path('please/', views.please, name="please"),
    # 영화 좋아요
    path('<int:movie_pk>/like/', views.movie_like, name="like"),
    # 추천알고리즘
    path('foryou/', views.foryou, name="foryou"),
    # 추천 메인화면
    path('recommendation/', views.recommendation, name='recommendation'),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'
urlpatterns = [
    # R: 리뷰 리스트를 보여주는 페이지
    path('', views.index, name='index'),
    # R: 특정 리뷰의 상세 내용을 보여주는 페이지  +  여기서 코멘트까지 처리
    path('<int:review_pk>/', views.review_detail, name="review_detail"),
    # C: 리뷰 작성(인자 = 영화pk)
    path('<int:movie_pk>/create/', views.review_create, name="review_create"),
    # U: 리뷰 수정
    path('<int:review_pk>/update/', views.review_update, name="review_update"),
    # D: 리뷰 삭제
    path('<int:review_pk>/delete/', views.review_delete, name="review_delete"),


    # 전체 리뷰 조회
    path('review_list/', views.review_list, name="review_list"),


    # -------------review좋아요----------- #
    path('<int:review_pk>/like/', views.review_like, name="review_like"),

    # -------------review 검색---------------- #
    path('find/', views.find, name="find"),
    path('find2/', views.find2, name="find2"),

    # -------------comment---------------- #
    path('<int:review_pk>/<int:comment_pk>/c_delete/', views.comment_delete, name='comment_delete'),
    # path('<int:review_pk>/<int:comment_pk>/c_update/', views.comment_update, name='comment_update'),
]

team/urls.py
from django.urls import path
from . import views

app_name = 'team'
urlpatterns = [
    path('', views.index, name='index'),
    path('intro/', views.intro, name='intro'),
]

movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=200)
    original_title = models.CharField(max_length=200, null=True)
    release_date = models.DateField(auto_now=False, null=True)
    popularity = models.FloatField(blank=True, null=True)
    vote_count = models.IntegerField(blank=True, null=True)
    vote_average = models.FloatField(blank=True, null=True)
    adult = models.BooleanField(blank=True, null=True)
    overview = models.TextField(blank=True, null=True)
    original_language = models.CharField(max_length=200, null=True)
    poster_path = models.CharField(max_length=255, blank=True, null=True)
    backdrop_path = models.CharField(max_length=255, blank=True, null=True)
    genres = models.ManyToManyField(Genre, related_name='movies')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies')

    def __str__(self):
        return self.title

class Moviestore(models.Model):
    title = models.CharField(max_length=200)
    original_title = models.CharField(max_length=200, null=True)
    release_date = models.DateField(auto_now=False, null=True)
    popularity = models.FloatField(blank=True, null=True)
    vote_count = models.IntegerField(blank=True, null=True)
    vote_average = models.FloatField(blank=True, null=True)
    adult = models.BooleanField(blank=True, null=True)
    overview = models.TextField(blank=True, null=True)
    original_language = models.CharField(max_length=200, null=True)
    poster_path = models.CharField(max_length=255, blank=True, null=True)
    backdrop_path = models.CharField(max_length=255, blank=True, null=True)
    genres = models.ManyToManyField(Genre, related_name='stored_movies')

    def __str__(self):
        return self.title

class MovieRatings(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    rater = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    score = models.IntegerField()
    def __str__(self):
        return self.movie.title

class PleaseAdd(models.Model):
    requester = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    movie_request = models.CharField(max_length=200)

    def __str__(self):
        return self.movie_request

class MovieLine(models.Model):
    movie = models.CharField(max_length=150)
    line = models.TextField()

    def __str__(self):
        return self.movie

movies/forms.py
from django import forms
from .models import PleaseAdd, MovieRatings, Moviestore

class PleaseAddForm(forms.ModelForm):
    class Meta:
        model = PleaseAdd
        fields = ('movie_request',)


class RateForm(forms.ModelForm):
    class Meta:
        model = MovieRatings
        fields = ('score',)
    
    score = forms.IntegerField(
        max_value = 10,
        min_value = 0,
        label = '평점',
        help_text = '0-10사이의 값으로 입력해주세요. 좋을 수록 큰 수:D',
        widget = forms.NumberInput(
            attrs={
                'placeholder':'☆☆☆☆☆☆☆☆☆☆'
            }
            )

    )


class MoviestoreForm(forms.ModelForm):
    class Meta:
        model = Moviestore
        fields = '__all__'

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.http import HttpResponse
from django.http import JsonResponse
from django.contrib.auth import get_user_model
from django.contrib import messages

from random import *
from rest_framework.response import Response
from rest_framework.decorators import api_view

from .models import Movie, MovieRatings, Moviestore,Genre
from .serializers import MovieSerializer
from .forms import PleaseAddForm, RateForm, MoviestoreForm


# 영화 메인화면 - 몇가지 추천 영화들 선보이기
def index(request):
    # 평점순 + 사람들이 많이 봄
    movies_rate = Movie.objects.filter(vote_average__gte=8.5).order_by('-vote_count')[:12]
    # 대중성
    movies_popular = Movie.objects.order_by('-popularity')[:12]
    # 한국영화 + 대중성
    movies_korea = Movie.objects.filter(original_language='ko').order_by('-popularity')[:12]
    # 오늘의 영화 : 평점 8 넘으면서, vote_count>= 4000, 최신순 정렬
    movies_recommend = Movie.objects.filter(vote_average__gte=8, vote_count__gte=4000).order_by('-release_date')
    genre = {
        "Adventure":12, "Fantasy":14, "Animation":16, "Drama":18, "Horror":27, "Action":28, 
        "Comedy":35, "History":36, "Western":37, "Thriller":53, "Crime":80, "Documentary":99, 
        "Science Fiction":878, "Mystery":9648, "Music":10402, "Romance":10749, "Family":10751, "War":10752, 
        "TV Movie":10770, 
    }
    # 장르별로 영화 하나 추천 -  대중성 면에서
    movies_genre = []
    for key, value in genre.items():
        movie = Movie.objects.filter(genres=value).order_by('-popularity')[0]
        movies_genre.append([movie,key])
        
    movie_num = randrange(0,80)
    choice = movies_recommend[movie_num]

    choice_genre = []
    c_genres = choice.genres.all()
    for value in c_genres.values():
        choice_genre.append(value)

    context = {
        'movies_rate' : movies_rate,
        'movies_popular' : movies_popular,
        'movies_korea' : movies_korea,
        'movies_genre' : movies_genre,
        'choice' : choice,
        'choice_genre':choice_genre,
    }
    return render(request, 'movies/index.html', context)

# 영화 상세보기
def m_detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk = movie_pk)
    count = movie.like_users.count()
    if request.user.is_authenticated:
        ratings = MovieRatings.objects.filter(rater=request.user, movie=movie)
        r = False
        if ratings:
            r = True
        context = {
            'count': count,
            'movie': movie,
            'r':r
        }
        return render(request, 'movies/m_detail.html', context)
    else:
        context = {
            'count': count,
            'movie': movie,
        }
        return render(request, 'movies/m_detail.html', context)

# 박스오피스 받아오기
import urllib.request as ul
import json
import datetime
from final.settings import BOXOFFICE_API_KEY

#박스오피스
def boxoffice(request):
    today = datetime.date.today()
    dd = today.strftime('%Y%m%d').split('-')
    day = int(dd[0]) - 1

    url = f"http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key={BOXOFFICE_API_KEY}&targetDt={day}"
    req = ul.Request(url)

    response = ul.urlopen(req)
    rescode = response.getcode()
    if(rescode == 200):
        responseData = response.read()
    result = json.loads(responseData)
    # print(result)
    movies = result['boxOfficeResult']['dailyBoxOfficeList']
    context = {
        'movies':movies,
    }
    return render(request, 'movies/boxoffice.html', context)

# 검색하는 페이지로 이동
def find(request):
    return render(request, 'movies/find.html')

# 검색결과 보여주는 페이지
def find2(request):
    b = request.GET.get('b','') # GET request의 인자중에 b 값이 있으면 가져오고, 없으면 빈 문자열 넣기
    if b: # b에 값이 들어있으면 true
        movies = Movie.objects.filter(Q(title__contains=b) | Q(original_title__contains=b)) 
    else:
        movies = '검색어와 일치하는 결과가 없습니다.'
    context = {
        'keyword':b,
        'movies': movies,
    }
    return render(request, 'movies/findresult.html', context)
 
# 일반 이용자가 영화DB 추가 요청
def please(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            form = PleaseAddForm(request.POST)
            if form.is_valid():
                please = form.save(commit=False)
                please.requester = request.user
                please.save()
                return render(request, 'movies/find.html')
        else:
            form = PleaseAddForm()
        context = {
            'form':form,
        }
        return render(request, 'accounts/form.html', context)
    else:
        return redirect('accounts:login')

# 영화 좋아요
def movie_like(request, movie_pk):
    if request.user.is_authenticated:
        user = request.user # 현재 로그인한 유저
        movie = get_object_or_404(Movie, pk=movie_pk)

        if movie.like_users.filter(pk=user.pk).exists():
            movie.like_users.remove(user) # 좋아요 취소
            liked = False
        else:
            movie.like_users.add(user) # 좋아요!
            liked = True
        count = movie.like_users.count()
        data = {
            'liked':liked,
            'count':count,
        }
        return JsonResponse(data)

def rate(request, movie_pk):
    if request.user.is_authenticated:
        if request.method == "POST":
            m = get_object_or_404(Movie, pk=movie_pk)
            form = RateForm(request.POST)
            if form.is_valid():
                rating = form.save(commit=False)
                rating.rater = request.user
                rating.movie = m
                rating.save()
                new_vote_average = (float(m.vote_average * m.vote_count) + rating.score) / (m.vote_count)
                new_vote_average = round(new_vote_average,1)
                m.vote_count = m.vote_count + 1
                m.vote_average = new_vote_average
                m.save()
                return redirect('movies:m_detail', movie_pk)
        else:
            form = RateForm()
        context = {
            'form' : form
        }
        return render(request, 'movies/forms.html', context)
    else:
        return redirect('accounts:login')

def rate_update(request, movie_pk):
    if request.user.is_authenticated:
        m = get_object_or_404(Movie, pk=movie_pk)
        ratedata = MovieRatings.objects.get(rater=request.user, movie=m)
        num = ratedata.score
        if request.method == "POST":
            form = RateForm(request.POST, instance = ratedata)
            if form.is_valid():
                rating = form.save(commit=False)
                rating.rater = request.user
                rating.movie = m
                rating.save()
                # 평점에 반영
                new_vote_average = (float(m.vote_average * m.vote_count) + (rating.score-num)) / (m.vote_count)
                new_vote_average = round(new_vote_average,1)
                m.vote_average = new_vote_average
                m.save()
                return redirect('movies:m_detail', movie_pk)
        else:
            form = RateForm(instance=ratedata)
        context = {
            'form' : form
        }
        return render(request, 'movies/forms.html', context)
    else:
        return redirect('accounts:login')

def rate_delete(request, movie_pk):
    if request.user.is_authenticated:
        m = get_object_or_404(Movie, pk=movie_pk)
        ratedata = MovieRatings.objects.get(rater=request.user, movie=m)
        # 기존 DB에서 이 평점의 영향 삭제
        total = (m.vote_average)*(m.vote_count)
        total -= ratedata.score
        m.vote_count -= 1
        m.vote_average = round(total/(m.vote_count),1)
        m.save()
        ratedata.delete()
        return redirect('movies:m_detail', movie_pk)
    else:
        return redirect('accounts:login')


# 추천 메인
def recommendation(request):
    num = randrange(0,499)
    # 무작위 추천
    movies1 = Movie.objects.order_by('-vote_count')[:500]
    randomone = movies1[num]
    # 괜찮은 추천
    movies2 = Movie.objects.filter(vote_count__gte=2000, vote_average__gte=8)
    many = movies2.count()
    num2 = randrange(0,many-1)
    notbadone = movies2[num2]
    context = {
        'random':randomone,
        'notbad':notbadone,
    }

    return render(request, 'movies/recommendation.html', context)


import pandas as pd
import math
import numpy as np
import operator

#### 추천알고리즘 ####

# 2. MovieRatings에 있는 모든 데이터를 딕셔너리 형태로 변환
def ratings_dict(mr):
    r_dict = {}
    for i in mr:
        if i.rater.pk not in r_dict.keys():
            r_dict[i.rater.pk]={i.movie.pk:float(i.score)}
        else:
            r_dict[i.rater.pk].setdefault(i.movie.pk,float(i.score))
    return r_dict

def cosine_similarity(A,B):
    A_norms = B_norms = 0
    dot_p = np.dot(A,B)
    A_norms = math.sqrt(sum([i**2 for i in A]))
    B_norms = math.sqrt(sum([i**2 for i in B]))
    AB_norms = A_norms * B_norms
    return dot_p / AB_norms # 1에 가까울수록 유사함.

# 3. KNN 기반의 사용자 기반 필터링 기법을 사용한 특정 유저에 대한 추천 영화.
def user_based_filtering(rating_dict, my, similarity=cosine_similarity, k=3):
    movies = Movie.objects.all()
    
    # db에 있는 모든 영화 데이터
    all_movie=[i.pk for i in movies]

    # (1) my(나)와 모든 사용자들이 내린 평가한 영화를 토대로 유사도를 계산한다.
    # my_rating: 내가 평점을 준 모든 영화 데이터
    my_rating = set(rating_dict[my].keys()) 
  
    similar_score={} # 사용자간 유사도 결과.
    for you in rating_dict.keys():
        if you != my:
            you_rating = set(rating_dict[you].keys())
            # (2) 나와 상대방의 교집합(intersection)를 찾는다.
            intersect = my_rating.intersection(you_rating)
            # (3) 겹치는게 최소 갯수 이상인 경우에만 유사도 측정 시작 
            if len(intersect) >= 3:
                
                # (4) 상대방과 나의 겹치는 영화의 평점을 추출해낸다
                my_rating_score = [rating_dict[my][i] for i in intersect]
                you_rating_score = [rating_dict[you][i] for i in intersect]
                # 2개의 데이터를 통해 유사도를 측정
                score= cosine_similarity(my_rating_score, you_rating_score)
    
                similar_score[you]=score
    
    # 유사도 정렬

movies/templates/movies/findresult.html
{% extends 'base.html' %}

{% block content %}
<!-- md보다 클때 -->
<!-- find2로 들어왔을 때 : 영화 검색창에 입력해서 들어온 경우 -->

<div class="d-none d-xl-block">
    <div class="my-4 mx-2 pt-5">
        <div class="d-flex pl-4 pr-4 align-items-end">
            <div class="mx-5 px-3 w-100">
                <div class="row red-line mb-2"></div>
                <div class="row today-choice-intro-sm mb-4">영화 DB 검색</div>
                <div class="row w-100">
                    <form class="form-inline my-2 my-md-0 w-100" method="get" action="{% url 'movies:find2' %}">
                        <input class="form-control w-75" type="text" placeholder="키워드 입력" aria-label="Search" name="b" value="{{b}}" style="filter: brightness(50%);">
                        <button class="btn btn-outline-secondary w-25">SEARCH:D</button>>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% if user.is_superuser %}
    <div class="my-4 mx-2 pt-5">
        <div class="d-flex pl-4 pr-4 align-items-end">
            <div class="mx-5 px-3 w-100">
                <div class="row red-line mb-2"></div>
                <div class="row today-choice-intro-sm mb-4">백업 DB 검색</div>
                <div class="row w-100">
                    <form class="form-inline my-2 my-md-0 w-100" method="get" action="{% url 'movies:find_store' %}">
                        <input class="form-control w-75" type="text" placeholder="키워드 입력" aria-label="Search" name="b" value="{{b}}" style="filter: brightness(50%);">
                        <button class="btn btn-outline-secondary w-25">SEARCH:D</button>>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    <div class="my-4 mx-2 pt-5">
        <div class="d-flex pl-4 pr-4 align-items-end">
            <div class="mx-5 px-3 w-100">
                <div class="row red-line mb-2"></div>
                <div class="row today-choice-intro-sm mb-4">검색 결과</div>
                {% if movies.count %}
                <div class="row w-100 mb-5 pb-5">
                    '{{ keyword }}' 에 대한 검색결과 입니다.
                </div>
                <div class="row w-100 mb-5 pb-5">
                    {% for movie in movies %}
                    <div class="col-4 row w-100 mx-0 my-3">
                        <div class="col-4"><img src="https://image.tmdb.org/t/p/original/{{ movie.poster_path }}" class="w-100" alt=""></div>
                        <div class="col-8">
                            <div class="row text-white">{{ movie.title }}</div>
                            <div class="row text-secondary">{{ movie.original_title }}</div>
                            <div class="row text-dark">RATING : {{ movie.vote_average }}</div>
                            <div class="row mt-3 justify-content-end my-2">
                                {% if request.resolver_match.url_name == 'find2' %}
                                <a href="{% url 'movies:m_detail' movie.pk %}"  class="btn w-50 btn-sm py-0 px-1 btn-outline-secondary text-white">영화 상세보기</a>
                                {% else %}
                                <a href="{% url 'movies:plus' movie.pk %}"  class="btn w-50 btn-sm py-0 px-1 btn-outline-secondary text-white">DB에 영화 추가</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <div class="row w-100 mb-4 text-muted justify-content-center">
                    '{{ keyword }}' 에 대한 검색결과가 없습니다.
                </div>
                <div class="row w-100 mb-5 pb-5 text-white justify-content-center">
                    <a href="{% url 'movies:please' %}" class="btn btn-outline-danger">영화 DB 업데이트 요청 보내기</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!-- md일때 -->
<div class="d-none d-md-block d-xl-none">
    <div class="my-4 mx-2 pt-5">
        <div class="d-flex pl-4 pr-4 align-items-end">
            <div class="mx-5 px-3 w-100">
                <div class="row red-line mb-2"></div>
                <div class="row today-choice-intro-sm mb-4">영화 DB 검색</div>
                <div class="row w-100">
                    <form class="form-inline my-2 my-md-0 w-100" method="get" action="{% url 'movies:find2' %}">
                        <input class="form-control w-75" type="text" placeholder="키워드 입력" aria-label="Search" name="b" value="{{b}}" style="filter: brightness(50%);">
                        <button class="btn btn-outline-secondary w-25">SEARCH:D</button>>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% if user.is_superuser %}
    <div class="my-4 mx-2 pt-5">
        <div class="d-flex pl-4 pr-4 align-items-end">
            <div class="mx-5 px-3 w-100">
                <div class="row red-line mb-2"></div>
                <div class="row today-choice-intro-sm mb-4">백업 DB 검색</div>
                <div class="row w-100">
                    <form class="form-inline my-2 my-md-0 w-100" method="get" action="{% url 'movies:find_store' %}">
                        <input class="form-control w-75" type="text" placeholder="키워드 입력" aria-label="Search" name="b" value="{{b}}" style="filter: brightness(50%);">
                        <button class="btn btn-outline-secondary w-25">SEARCH:D</button>>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    <div class="my-4 mx-2 pt-5">
        <div class="d-flex pl-4 pr-4 align-items-end">
            <div class="mx-5 px-3 w-100">
                <div class="row red-line mb-2"></div>
                <div class="row today-choice-intro-sm mb-4">검색 결과</div>
                {% if movies.count %}
                <div class="row w-100 mb-5 pb-1">
                    '{{ keyword }}' 에 대한 검색결과 입니다.
                </div>
                <div class="row w-100 mb-5 pb-5">
                    {% for movie in movies %}
                    <div class="col-6 row w-100 mx-0 my-3">
                        <div class="col-4"><img src="https://image.tmdb.org/t/p/original/{{ movie.poster_path }}" class="w-100" alt=""></div>
                        <div class="col-8">
                            <div class="row text-white">{{ movie.title }}</div>
                            <div class="row text-secondary">{{ movie.original_title }}</div>
                            <div class="row text-dark">RATING : {{ movie.vote_average }}</div>
                            <div class="row mt-3 justify-content-end my-2">
                                {% if request.resolver_match.url_name == 'find2' %}
                                <a href="{% url 'movies:m_detail' movie.pk %}"  class="btn w-25 btn-sm py-0 px-1 btn-outline-secondary text-white">영화 상세보기</a>
                                {% else %}
                                <a href="{% url 'movies:plus' movie.pk %}"  class="btn w-25 btn-sm py-0 px-1 btn-outline-secondary text-white">DB에 영화 추가</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <div class="row w-100 mb-4 text-muted justify-content-center">
                    '{{ keyword }}' 에 대한 검색결과가 없습니다.
                </div>
                <div class="row w-100 mb-5 pb-5 text-white justify-content-center">
                    <a href="{% url 'movies:please' %}" class="btn btn-outline-danger">영화 DB 업데이트 요청 보내기</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!-- md보다 작을때 -->
<div class="d-block d-md-none mt-5">
    <div class="d-flex pl-4 pr-4 align-items-end">
        <div class="container w-100">
            <div class="row red-line mb-2"></div>
            <div class="row today-choice-intro-sm mb-4">영화 DB 검색</div>
            <div class="row w-100 mx-0">
                <form class="form-inline w-100 my-2 my-md-0" method="get" action="{% url 'movies:find2' %}">
                    <input class="form-control w-75" type="text" placeholder="Search" aria-label="Search" name="b" value="{{b}}" style="filter: brightness(50%);">
                    <button class="btn btn-outline-secondary w-25"><img src="/static/img/search.png" alt="search" height="15px"></button>>
                </form>
            </div>
        </div>
    </div>
</div>
{% if user.is_superuser %}
<div class="d-block d-md-none mt-5">
    <div class="d-flex pl-4 pr-4 align-items-end">
        <div class="container w-100">
            <div class="row red-line mb-2"></div>
            <div class="row today-choice-intro-sm mb-4">백업 DB 검색</div>
            <div class="row w-100 mx-0">
                <form class="form-inline w-100 my-2 my-md-0" method="get" action="{% url 'movies:find_store' %}">
                    <input class="form-control w-75" type="text" placeholder="Search" aria-label="Search" name="b" value="{{b}}" style="filter: brightness(50%);">
                    <button class="btn btn-outline-secondary w-25"><img src="/static/img/search.png" alt="search" height="15px"></button>>
                </form>
            </div>
        </div>
    </div>
</div>
{% endif %}
<div class="d-block d-md-none my-5 pb-5">
    <div class="d-flex pl-4 pr-4 align-items-end">
        <div class="container w-100">
            <div class="row red-line mb-2"></div>
            <div class="row today-choice-intro-sm mb-4">검색 결과</div>
            {% if movies.count %}
            <div class="row w-100 mb-5 pb-5">
                '{{ keyword }}' 에 대한 검색결과 입니다.
            </div>
            {% for movie in movies %}
            <div class="row w-100 mx-0 my-3">
                <div class="col-4"><img src="https://image.tmdb.org/t/p/original/{{ movie.poster_path }}" class="w-100" alt=""></div>
                <div class="col-8">
                    <div class="row text-white">{{ movie.title }}</div>
                    <div class="row text-secondary">{{ movie.original_title }}</div>
                    <div class="row text-dark">RATING : {{ movie.vote_average }}</div>
                    <div class="row mt-3 justify-content-end my-2">
                        {% if request.resolver_match.url_name == 'find2' %}
                        <a href="{% url 'movies:m_detail' movie.pk %}"  class="btn w-100 btn-sm py-0 px-1 btn-outline-secondary text-secondary">영화 상세보기</a>
                        {% else %}
                        <a href="{% url 'movies:plus' movie.pk %}"  class="btn w-100 btn-sm py-0 px-1 btn-outline-secondary text-secondary">DB에 영화 추가</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% else %}
        <div class="row container mb-4 text-muted justify-content-center text-center">
            '{{ keyword }}' 에 대한 검색결과가 없습니다.
        </div>
        <div class="row w-100 mb-5 pb-5 text-white justify-content-center">
            <a href="{% url 'movies:please' %}" class="btn btn-outline-danger">영화 DB 업데이트 요청 보내기</a>
        </div>
        {% endif %}        
    </div>
</div>

{% endblock %}