accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    # /accounts/
    # path('',views.index, name='index'),
    path('signup/',views.signup, name='signup'),
    path('login/',views.login, name = 'login'),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name='delete'),
    # path('update/', views.update,name='update'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),

]

final/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.main),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('reviews/', include('reviews.urls')),
    path('accounts/',include('accounts.urls')),
    path('team/', include('team.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name='movies'
urlpatterns = [
    # 메인, 상세보기, 박스오피스
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.m_detail, name="m_detail"),
    path('boxoffice/', views.boxoffice, name="boxoffice"),
    
    # 영화 검색 - 입력 & 결과
    path('find/', views.find, name="find"),
    path('find2/', views.find2, name="find2"),

    # 영화 추가
    path('<int:movie_pk>/plus/', views.plus, name="plus"),
    path('find_store/', views.find_store, name="find_store"),


    # ----------- 혜민
    path('<int:movie_pk>/rate/', views.rate, name="rate"),
    path('<int:movie_pk>/rate_update/', views.rate_update, name="rate_update"),
    path('<int:movie_pk>/rate_delete/', views.rate_delete, name="rate_delete"),

    # 영화 요청
    path('please/', views.please, name="please"),
    # 영화 좋아요
    path('<int:movie_pk>/like/', views.movie_like, name="like"),
    # 추천알고리즘
    path('foryou/', views.foryou, name="foryou"),
    # 추천 메인화면
    path('recommendation/', views.recommendation, name='recommendation'),
]

team/urls.py
from django.urls import path
from . import views

app_name = 'team'
urlpatterns = [
    path('', views.index, name='index'),
    path('intro/', views.intro, name='intro'),
]

reviews/models.py
from django.db import models
from movies.models import Movie
from django.conf import settings

# Create your models here.
class Review(models.Model):
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    # star = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')

    def __str__(self):
        return self.title


class Comment(models.Model):
    c_writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    content = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    clike_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments')

    def __str__(self):
        return self.content

team/models.py
from django.db import models

# Create your models here.

team/views.py
from django.shortcuts import render
from movies.models import PleaseAdd, MovieLine, MovieRatings
from random import *

# Create your views here.
def index(request):
    lines = MovieLine.objects.all()
    luckynum = randrange(0,len(lines)-1)
    goodline = lines[luckynum]

    if request.user.is_authenticated:
        # 사용자가 DB추가 요청한 영화들
        moviecnt = request.user.movieratings_set.count()
        requests = PleaseAdd.objects.filter(requester = request.user)
        requests_cnt = requests.count()
        cnt = 0
        reviews = request.user.review_set.all()
        for review in reviews:
            cnt += review.like_users.count()
        cnt += reviews.count()
        cnt += request.user.comment_set.count()
        # point = 리뷰수 + 리뷰에 받은 좋아요 수 + 자기가 단 코멘트 개수
        context =  {
            'cnt' : cnt,
            'requests': requests,
            'requests_cnt': requests_cnt,
            'goodline':goodline,
            'moviecnt':moviecnt,
        }
        return render(request, 'team/index.html', context)
    else:
        context = {
            'goodline':goodline,
        }
        return render(request, 'team/index.html', context)

def intro(request):
    return render(request, 'team/intro.html')

def myinfo(request):
    requests = PleaseAdd.objects.filter(requester = request.user)
    context = {
        'requests':requests,
    }
    return render(request, '')

team/templates/team/index.html
{% extends 'base.html' %}

{% block content %}
<!-- 크기 클 때 -->
<div class="d-none d-md-block mb-5 pb-5">
    <div class="container pt-5 mt-3">
        {% if request.user.is_authenticated %}
        <div class="row">
            <div class="offset-1 col-3"><img src="/static/img/profile/member.png" alt="user" width="150px"></div>
            <div class="col-8">
                <div class="row team-profile-name-lg">{{ request.user.username }} 님,</div>
                <div class="row team-profile-hello-lg mt-3">TWEEZERS와 함께 즐거운 하루 보내세요 :)</div>
                <div class="row team-profile-follower-lg">FOLLOWERS : {{ request.user.followers.count }} | FOLLOWINGS : {{ request.user.followings.count }} </div>
            </div>
        </div>
        <div class="row pb-5 my-5 justify-content-center">
            <div class="col-3">
                <div class="row justify-content-center team-profile-object-lg">MOVIE</div>
                <div class="row justify-content-center team-profile-cnt-lg">{{ moviecnt }}</div>
            </div>
            <div class="col-3">
                <div class="row justify-content-center team-profile-object-lg">REVIEW</div>
                <div class="row justify-content-center team-profile-cnt-lg">{{ request.user.review_set.count }}</div>
            </div>
            <div class="col-3">
                <div class="row justify-content-center team-profile-object-lg">COMMENT</div>
                <div class="row justify-content-center team-profile-cnt-lg">{{ request.user.comment_set.count }}</div>
            </div>
            <div class="col-3">
                <div class="row justify-content-center team-profile-object-lg">POINT</div>
                <div class="row justify-content-center team-profile-cnt-lg">{{ cnt }}</div>
            </div>
        </div>
        <div class="row mt-5 pt-5 mx-3">
            <div class="container">
                <div class="px-3 w-100">
                    <div class="row red-line mb-2"></div>
                    <div class="row today-choice-intro-sm mb-4 w-100">실시간 명대사</div>
                    <div class="row w-100 pl-3 justify-content-start text-secondary team-profile-setting-lg text-warning ml-3 mt-5">「 {{ goodline.movie }} 」</div>
                    <div class="row w-100 pl-3 justify-content-start text-secondary team-profile-setting-lg mt-3 ml-3">{{ goodline.line }}</div>
                </div>
            </div>
        </div>
        <div class="row mt-5 pt-5 mx-3">
            <div class="container">
                <div class="px-3 w-100">
                    <div class="row red-line mb-2"></div>
                    <div class="row today-choice-intro-sm mb-4 w-100">계정 설정</div>
                    <div class="row w-100 pl-3 justify-content-start text-secondary team-profile-setting-lg"><a href="{% url 'accounts:logout' %}" class="text-secondary team-profile-setting-lg"> ▶ 로그아웃</a></div>
                </div>
            </div>
        </div>
        {% else %}
        <div class="row">
            <div class="offset-1 col-3"><img src="/static/img/profile/anonymous.png" alt="anonymous user" width="150px"></div>
            <div class="col-8">
                <div class="row team-profile-name-lg">반갑습니다! 고객님,</div>
                <div class="row team-profile-hello-lg mt-3">TWEEZERS와 함께 즐거운 하루 보내세요 :)</div>
                <div class="row team-profile-ex-lg mt-3">TWEEZERS는 영화 순위와 상세 정보를 포함해 영화에 관련된</div>
                <div class="row team-profile-ex-lg ">추천, 커뮤니티 서비스를 제공하는 통합적인 컨텐츠 플랫폼 입니다.</div>
            </div>
        </div>
        <div class="row mt-5 pt-5 mx-3">
            <div class="container">
                <div class="px-3 w-100">
                    <div class="row red-line mb-2"></div>
                    <div class="row today-choice-intro-sm mb-4 w-100">실시간 명대사</div>
                    <div class="row w-100 pl-3 justify-content-start text-secondary team-profile-setting-lg text-warning">「 {{ goodline.movie }} 」</div>
                    <div class="row w-100 pl-3 justify-content-start text-secondary team-profile-setting-lg">{{ goodline.line }}</div>
                </div>
            </div>
        </div>
        <div class="row mt-5 pt-5 mx-3">
            <div class="container">
                <div class="px-3 w-100">
                    <div class="row red-line mb-2"></div>
                    <div class="row today-choice-intro-sm mb-4 w-100">계정 설정</div>
                    <div class="row w-100 pl-3 justify-content-start text-secondary"><a href="{% url 'accounts:login' %}" class=" team-profile-setting-lg"> ▶ 로그인</a></div>
                    <div class="row w-100 pl-3 justify-content-start text-secondary"><a href="{% url 'accounts:signup' %}" class=" team-profile-setting-lg"> ▶ 회원가입</a></div>
                </div>
            </div>
        </div>
        {% endif %}
        <div class="row mt-5 pt-5 mx-3">
            <div class="container">
                <div class="px-3 w-100">
                    <div class="row red-line mb-2"></div>
                    <div class="row today-choice-intro-sm mb-4 w-100">고객지원</div>
                    <div class="row w-100 justify-content-between d-flex text-secondary">
                        <div class="team-profile-setting-lg"> ▶ 버전 정보</div>
                        <div>1.0.0</div>
                    </div>
                    <div class="row team-content"><a href="{% url 'team:intro' %}" class="team-profile-setting-lg"> ▶ TWEEZERS 소개</a></div>
                    <div class="row team-content team-profile-setting-lg"><a href="" class="team-content team-profile-setting-lg"> ▶ 오픈소스라이선스</a></div>
                    <div class="row text-secondary pl-4">- tmdb api</div>
                    <div class="row text-secondary pl-4">- 영화진흥위원회 api</div>
                    <div class="row text-secondary pl-4">- animate.css</div>
                    <div class="row text-secondary pl-4">- bootstrap</div>
                    <div class="row text-secondary pl-4">- flaticon</div>
                    <div class="row text-secondary pl-4">- https://unsplash.com</div>
                    <div class="row text-secondary pl-4">- http://websitename.com/favicon.ico</div>
                </div>
            </div>
        </div>
        {% if request.user.is_authenticated %}
        <div class="row my-5 py-5 mx-3">
            <div class="container">
                <div class="px-3 w-100">
                    <div class="row red-line mb-2"></div>
                    <div class="row today-choice-intro-sm mb-4 w-100">My Info</div>
                    {% if request_cnt != 0 %}
                        <div class="team-profile-setting-lg row mb-2">▶ 총 {{ requests_cnt }} 편의 영화 요청</div>
                        {% for r in requests %}
                        <div class="row text-secondary pl-4">- {{ r.movie_request }}</div>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
        {% endif %}
    </div>

</div>
<!-- 크기 작을 때 -->
<div class="d-block d-md-none mb-5 mybox">
    {% if request.user.is_authenticated %}
    <div class="row justify-content-center team-intro">{{ request.user.username }}, Have a nice day :)</div>
    <div class="row team-profile-box">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-4"><img src="/static/img/profile/member.png" class="w-100" alt="user"></div>
                <div class="col-8 pl-4">
                    <div class="row team-profile-name mt-3">ID : {{ request.user.username }}</div>
                    <div class="row team-profile-info">FOLLOWERS : {{ request.user.followers.all.count }}</div>
                    <div class="row team-profile-info">FOLLOWINGS : {{ request.user.followings.all.count }}</div>
                    <div class="row team-profile-info">REVIEWS : {{ request.user.review_set.all.count }}</div>
                    <div class="row team-profile-info">POINTS : {{ cnt }}</div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-4">
            <div class="team-profile-item text-center px-0">Movies</div>
            <div class="team-profile-item-data text-center px-0">{{ moviecnt }}</div>
        </div>
        <div class="col-4">
            <div class="team-profile-item text-center px-0">Reviews</div>
            <div class="team-profile-item-data text-center px-0">{{ request.user.review_set.all.count }}</div>
        </div>
        <div class="col-4">
            <div class="team-profile-item text-center px-0">Comments</div>
            <div class="team-profile-item-data text-center px-0">{{ request.user.comment_set.all.count }}</div>
        </div>
    </div>
    {% else %}
    <div class="row team-intro justify-content-center ">Welcome to TWEEZERS :)</div>
    {% endif %}
    <div class="my-4 mx-2 pt-3">
        <div class="d-flex mt-5 pl-4 pr-4 align-items-end">
            <div class="container">
                <div class="row red-line mb-2"></div>
                <div class="row today-choice-intro-sm mb-4">실시간 명대사</div>
                <div class="row mt-3 team-content text-warning ml-2">「 {{ goodline.movie }} 」</div>
                <div class="row mt-3 team-content mx-3">{{ goodline.line }}</div>
            </div>
        </div>
        <div class="d-flex mt-5 pl-4 pr-4 align-items-end">
            <div class="container">
                <div class="row red-line mb-2"></div>
                <div class="row today-choice-intro-sm mb-4">계정 설정</div>
                {% if request.user.is_authenticated %}
                <div class="row mt-3 team-content"><a href="{% url 'accounts:logout' %}" class="team-content">▶ 로그아웃</a></div>
                {% else %}
                <div class="row mt-3 team-content"><a href="{% url 'accounts:signup' %}" class="team-content">▶ 회원가입</a></div>
                <div class="row team-content"><a href="{% url 'accounts:login' %}" class="team-content"> ▶ 로그인</a></div>
                {% endif %}
            </div>
        </div>
        <div class="d-flex mt-5 pl-4 pr-4 align-items-end">
            <div class="container">
                <div class="row red-line mb-2"></div>
                <div class="row today-choice-intro-sm mb-4">고객 지원</div>
                <div class="row mt-3 mb-2 team-content d-flex justify-content-between">
                    <div class="mx-2"> ▶ 버전 정보</div>
                    <div>1.0.0</div>
                </div>
                <div class="row team-content"><a href="{% url 'team:intro' %}" class="team-content"> ▶ TWEEZERS 소개</a></div>
                <div class="row team-content"><a href="" class="team-content"> ▶ 오픈소스라이선스</a></div>
                <div class="row text-secondary pl-4">- tmdb api</div>
                <div class="row text-secondary pl-4">- 영화진흥위원회 api</div>
                <div class="row text-secondary pl-4">- animate.css</div>
                <div class="row text-secondary pl-4">- bootstrap</div>
                <div class="row text-secondary pl-4">- flaticon</div>
                <div class="row text-secondary pl-4">- https://unsplash.com</div>
                <div class="row text-secondary pl-4">- http://websitename.com/favicon.ico</div>
            </div>
        </div>
        {% if request.user.is_authenticated %}
        <div class="d-flex mt-5 pl-4 pr-4 align-items-end pb-5">
            <div class="container">
                <div class="row red-line mb-2"></div>
                <div class="row today-choice-intro-sm mb-4">My Info</div>
                {% if request_cnt != 0 %}
                    <div class="row team-content mx-1">▶ 총 {{ requests_cnt }} 편의 영화 요청</div>
                    {% for r in requests %}
                    <div class="row text-secondary pl-4">- {{ r.movie_request }}</div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        {% endif %}
    </div>
</div>


{% endblock %}

team/templates/team/intro.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TWEEZERS</title>
    <link rel="icon" type="image/png" sizes="16x16" href="/static/img/favicon-16x16.png">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
    <div class="company-intro d-flex justify-content-center align-items-center">
        <div class="company-explain w-75 h-75 d-flex align-items-center">
            <div class="container">
                <dic class="row h-100 d-flex align-items-stratch">
                    <div class="col-12 w-100 text-center px-0 company-intro-logo mb-3"><img src="/static/img/logo.png" class="company-intro-logoimg" alt="logo">TWEEZERS</div>
                    <div class="col-12 w-100 text-center px-0 company-intro-title1 mb-1">사용자에게</div>
                    <div class="col-12 w-100 text-center px-0 company-intro-title1 mb-1"><span class="text-warning">꼭</span> 맞는 영화를</div>
                    <div class="col-12 w-100 text-center px-0 company-intro-title1 mb-4"><span class="text-warning">콕</span> 집어 추천!</div>
                    <div class="col-12 w-100 text-center px-0 company-intro-title2 pt-3 ">트위저스는 영화 정보와 순위를 포함</div>
                    <div class="col-12 w-100 text-center px-0 company-intro-title2">추천, 커뮤니티 서비스를 제공하는</div>
                    <div class="col-12 w-100 text-center px-0 company-intro-title2 mb-5 pb-5">통합적인 영화 컨텐츠 플랫폼입니다.</div>
                    <div class="col-12 w-100 text-center px-0"><a href="{% url 'movies:index' %}" class="company-intro-tohome-ex"><img src="/static/img/bottomnav/home.png" class="company-intro-tohome mx-2" alt="">영화 메인으로 돌아가기</a></div>
                </dic>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>