final/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.main),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('reviews/', include('reviews.urls')),
    path('accounts/',include('accounts.urls')),
    path('team/', include('team.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name='movies'
urlpatterns = [
    # 메인, 상세보기, 박스오피스
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.m_detail, name="m_detail"),
    path('boxoffice/', views.boxoffice, name="boxoffice"),
    
    # 영화 검색 - 입력 & 결과
    path('find/', views.find, name="find"),
    path('find2/', views.find2, name="find2"),

    # 영화 추가
    path('<int:movie_pk>/plus/', views.plus, name="plus"),
    path('find_store/', views.find_store, name="find_store"),


    # ----------- 혜민
    path('<int:movie_pk>/rate/', views.rate, name="rate"),
    path('<int:movie_pk>/rate_update/', views.rate_update, name="rate_update"),
    path('<int:movie_pk>/rate_delete/', views.rate_delete, name="rate_delete"),

    # 영화 요청
    path('please/', views.please, name="please"),
    # 영화 좋아요
    path('<int:movie_pk>/like/', views.movie_like, name="like"),
    # 추천알고리즘
    path('foryou/', views.foryou, name="foryou"),
    # 추천 메인화면
    path('recommendation/', views.recommendation, name='recommendation'),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'
urlpatterns = [
    # R: 리뷰 리스트를 보여주는 페이지
    path('', views.index, name='index'),
    # R: 특정 리뷰의 상세 내용을 보여주는 페이지  +  여기서 코멘트까지 처리
    path('<int:review_pk>/', views.review_detail, name="review_detail"),
    # C: 리뷰 작성(인자 = 영화pk)
    path('<int:movie_pk>/create/', views.review_create, name="review_create"),
    # U: 리뷰 수정
    path('<int:review_pk>/update/', views.review_update, name="review_update"),
    # D: 리뷰 삭제
    path('<int:review_pk>/delete/', views.review_delete, name="review_delete"),


    # 전체 리뷰 조회
    path('review_list/', views.review_list, name="review_list"),


    # -------------review좋아요----------- #
    path('<int:review_pk>/like/', views.review_like, name="review_like"),

    # -------------review 검색---------------- #
    path('find/', views.find, name="find"),
    path('find2/', views.find2, name="find2"),

    # -------------comment---------------- #
    path('<int:review_pk>/<int:comment_pk>/c_delete/', views.comment_delete, name='comment_delete'),
    # path('<int:review_pk>/<int:comment_pk>/c_update/', views.comment_update, name='comment_update'),
]

team/urls.py
from django.urls import path
from . import views

app_name = 'team'
urlpatterns = [
    path('', views.index, name='index'),
    path('intro/', views.intro, name='intro'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TWEEZERS</title>
    <link rel="icon" type="image/png" sizes="16x16" href="/static/img/favicon-16x16.png">
    <link rel="stylesheet" href="{% static 'css/review_index.css' %}">
    <link rel="stylesheet" href="{% static 'css/team.css' %}">
    <link rel="stylesheet" href="{% static 'css/review_detail.css' %}">
    <link rel="stylesheet" href="{% static 'css/boxoffice.css' %}">
    <link rel="stylesheet" href="{% static 'css/movie_detail.css' %}">
    <link rel="stylesheet" href="{% static 'css/movie_index.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
    <div class="d-none d-md-block navbox">
        <nav class="top-navbar d-flex justify-content-between">
            <div class="left-nav">
                <div class="left-nav-item">
                    <div class="left-nav-logo"><a href="/" class="left-nav-logo"><img src="/static/img/logo2.png" alt="" height="35px" class="nav-search-img">TWEEZERS</a></div>
                    <small class="left-nav-logo-ex ml-1" style="letter-spacing: 0.15rem; color: grey;">BEST MOVIE PICKER FOR YOU</small>
                </div>
            </div>
            <div class="right-nav">
                <ul class="right-nav-items d-flex">
                    <li class="right-nav-item"><a href="{% url 'movies:index' %}" class="nav-link">MOVIES</a></li>
                    <li class="right-nav-item"><a href="{% url 'movies:boxoffice' %}" class="nav-link">BOXOFFICE</a></li>
                    <li class="right-nav-item"><a href="{% url 'movies:recommendation' %}" class="nav-link">FOR YOU</a></li>
                    <li class="right-nav-item"><a href="{% url 'reviews:index' %}" class="nav-link">REVIEW</a></li>
                    <li class="right-nav-item"><a href="{% url 'movies:find' %}" class="nav-link"><img src="/static/img/search.png" alt="" height="22px" class="nav-search-img"></a></li>
                    <li class="right-nav-item"><a href="{% url 'team:index' %}" class="nav-link"><img src="/static/img/menu1.png" alt="" height="25px" class="nav-profile-img"></a></li>
                </ul>
            </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
    <div class="bottom-nav d-block d-lg-none">
        <nav class="bottom-navbar fixed-bottom">
            <ul class="bottom-nav-items d-flex justify-content-around">
                <li class="bottom-nav-item">
                    <a href="{% url 'movies:index' %}" class="bottom-nav-item-link">
                        <div class="text-center"><img src="/static/img/bottomnav/movies.png" width="30px"alt=""></div>
                        <div class="bottom-nav-item-ex text-center">MOVIES</div>
                    </a>
                </li>
                <li class="bottom-nav-item">
                    <a href="{% url 'movies:boxoffice' %}" class="bottom-nav-item-link">
                        <div class="text-center"><img src="/static/img/bottomnav/chart.png" width="30px" alt=""></div>
                        <div class="bottom-nav-item-ex text-center">BOXOFFICE</div>
                    </a>
                </li>
                <li class="bottom-nav-item">
                    <a href="{% url 'movies:recommendation' %}" class="bottom-nav-item-link">
                        <div class="text-center"><img src="/static/img/bottomnav/recommendation.png" width="30px" alt=""></div>
                        <div class="bottom-nav-item-ex text-center">For YOU</div>
                    </a>
                </li>
                <li class="bottom-nav-item">
                    <a href="{% url 'reviews:index' %}" class="bottom-nav-item-link">
                        <div class="text-center"><img src="/static/img/bottomnav/community.png" width="30px" alt=""></div>
                        <div class="bottom-nav-item-ex text-center">COMMUNITY</div>
                    </a>
                </li>
                <li class="bottom-nav-item">
                    <a href="{% url 'team:index' %}" class="bottom-nav-item-link">
                        <div class="text-center"><img src="/static/img/bottomnav/menu.png" width="30px" alt=""></div>
                        <div class="bottom-nav-item-ex text-center">MENU</div>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.0"></script>
</body>
</html>

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TWEEZERS</title>
    <link rel="icon" type="image/png" sizes="16x16" href="/static/img/favicon-16x16.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body class="main-body">
    <div class="our-main">
        <div class="row text-center h-100 mw-100 d-flex justify-content-center align-items-center">
            <a href="{% url 'movies:index' %}" class="our-main-url">
                <div class="col-12 text-center d-flex justify-content-center">
                    <div>
                        <div class="animate__animated animate__slideInDown animate__slow our-main-logoex text-right mt-3">THE BEST MOVIE PLATFORM</div>
                        <div class="animate__animated animate__slideInDown animate__slow our-main-logoname">TWEEZERS</div>
                    </div>
                    <div><img src="/static/img/logo2.png" class="animate__animated animate__slideInDown animate__slow our-main-img" width="100px" alt=""></div>
                </div>
                <button class="col-12 btn btn-outline-dark text-secondary mt-2 animate__animated animate__flash animate__delay-2s">HOME</button>
            </a>
        </div>
    </div>
    <div>

    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>